/**:
    controller_manager:
      ros__parameters:
        update_rate: 50

        joint_state_broadcaster:
          type: joint_state_broadcaster/JointStateBroadcaster
        
        diff_drive_controller:
          type: diff_drive_controller/DiffDriveController

    diff_drive_controller:
      ros__parameters: 
        left_wheel_names: ["front_left_wheel", "rear_left_wheel"]
        right_wheel_names: ["front_right_wheel", "rear_right_wheel"]

        wheel_separation: 0.31
        wheel_radius: 0.098
        wheels_per_side: 1

        odom_frame_id: "odom"
        base_frame_id: "base_link"

        pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
        twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

        use_stamped_vel: false
        enable_odom_tf: false



