- ros_topic_name: '/clock'
  gz_topic_name: '/clock'
  ros_type_name: 'rosgraph_msgs/msg/Clock'
  gz_type_name: 'gz.msgs.Clock'
  direction: GZ_TO_ROS

- ros_topic_name: '/imu'
  gz_topic_name: '/imu'
  ros_type_name: 'sensor_msgs/msg/Imu'
  gz_type_name: 'ignition.msgs.IMU'
  direction: GZ_TO_ROS

- ros_topic_name: '/scan'
  gz_topic_name: '/lidar'
  ros_type_name: 'sensor_msgs/msg/LaserScan'
  gz_type_name: 'ignition.msgs.LaserScan'
  direction: GZ_TO_ROS

- ros_topic_name: '/scan/points'
  gz_topic_name: '/lidar/points'
  ros_type_name: 'sensor_msgs/msg/PointCloud2'
  gz_type_name: 'ignition.msgs.PointCloudPacked'
  direction: GZ_TO_ROS