/**:
  controller_manager:
    ros__parameters:
      update_rate: 100  # Hz

      # Joint State Broadcaster
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      # Jackal Diff Drive Controller
      diff_drive_controller:
        type: diff_drive_controller/DiffDriveController

      # UR5 Arm Joint Trajectory Controller
      arm_controller:
        type: forward_command_controller/ForwardCommandController


  # Jackal Differential Drive Controller Configuration
  diff_drive_controller:
    ros__parameters:
      left_wheel_names: ["mobman_front_left_wheel", "mobman_rear_left_wheel"]
      right_wheel_names: ["mobman_front_right_wheel", "mobman_rear_right_wheel"]

      wheel_separation: 0.37559
      wheel_radius: 0.098

      wheel_separation_multiplier: 1.0
      left_wheel_radius_multiplier: 1.0
      right_wheel_radius_multiplier: 1.0

      publish_rate: 50.0
      odom_frame_id: odom
      base_frame_id: mobman_base_link
      pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
      twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

      
      use_stamped_vel: false


  # UR5 Arm Joint Trajectory Controller Configuration
  arm_controller:
    ros__parameters:
      joints: ['mobman_ur5_base_link1_joint', 'mobman_ur5_link1_link2p1_joint', 'mobman_ur5_link2p3_link3_joint', 'mobman_ur5_link3_link4_joint', 'mobman_ur5_link4_link5_joint', 'mobman_ur5_link5_link6_joint']
      interface_name: 'position'