- ros_topic_name: '/clock'
  gz_topic_name: '/clock'
  gz_type_name: 'gz.msgs.Clock'
  direction: GZ_TO_ROS

- ros_topic_name: '/ur5/camera/camera_info'
  gz_topic_name: '/ur5/camera/camera_info'
  ros_type_name: 'sensor_msgs/msg/CameraInfo'
  gz_type_name: 'ignition.msgs.CameraInfo'
  direction: GZ_TO_ROS

- ros_topic_name: '/ur5/camera/image_raw'
  gz_topic_name: '/ur5/camera/image_raw'
  ros_type_name: 'sensor_msgs/msg/Image'
  gz_type_name: 'ignition.msgs.Image'
  direction: GZ_TO_ROS

- ros_topic_name: '/ur5/depth_camera/camera_info'
  gz_topic_name: '/ur5/depth_camera/camera_info'
  ros_type_name: 'sensor_msgs/msg/CameraInfo'
  gz_type_name: 'ignition.msgs.CameraInfo'
  direction: GZ_TO_ROS

- ros_topic_name: '/ur5/depth_camera/depth_image'
  gz_topic_name: '/ur5/depth_camera/depth_image'
  ros_type_name: 'sensor_msgs/msg/Image'
  gz_type_name: 'ignition.msgs.Image'
  direction: GZ_TO_ROS

- ros_topic_name: '/ur5/depth_camera/image'
  gz_topic_name: '/ur5/depth_camera/image'
  ros_type_name: 'sensor_msgs/msg/Image'
  gz_type_name: 'ignition.msgs.Image'
  direction: GZ_TO_ROS

- ros_topic_name: '/ur5/depth_camera/points'
  gz_topic_name: '/ur5/depth_camera/points'
  ros_type_name: 'sensor_msgs/msg/PointCloud2'
  gz_type_name:  'ignition.msgs.PointCloudPacked'
  direction: GZ_TO_ROS